import { Personne } from './personne';

export const personnes: Personne[] = [
  {
    id: 0,
    firstName: 'Alice',
    lastName: 'Jones',
    age: 35,
    picture:
      'https://th.bing.com/th/id/R.53bb1512421aa9534427a4b0e62f5aa1?rik=H2BmPf2jcnfhPg&riu=http%3a%2f%2fimagesolutions.ca%2fwp-content%2fuploads%2f2016%2f01%2fDSC02624-Edit.jpg&ehk=NTIVsJxrfayk9LEHelSQ8%2f0ooZ6dFVw8PMFJH%2fOcv1Q%3d&risl=&pid=ImgRaw&r=0',
    email: 'alice.jones@test.com',
    phone: '555-7890',
    address: '456 Elm St',
    created: new Date(),
    categorie: 'ingenieur',
  },

  {
    id: 1,
    firstName: 'John',
    lastName: 'Smith',
    age: 96,
    picture:
      'https://img.freepik.com/psd-gratuit/personne-celebrant-son-orientation-sexuelle_23-2150115662.jpg',
    email: 'gary.smith@mail.com',
    phone: '555-7890',
    address: '123 Main St',
    created: new Date(),
    categorie: 'dev',
  },

  {
    id: 2,
    firstName: 'Bob',
    lastName: 'Brown',
    age: 68,
    picture:
      'https://th.bing.com/th?id=OIP.GpJANSndGBU3TMsc4jaXcAHaLH&w=204&h=306&c=8&rs=1&qlt=90&o=6&dpr=1.5&pid=3.1&rm=2',
    email: 'anna.davis@mail.com',
    phone: '555-7890',
    address: '123 Main St',
    created: new Date(),
    categorie: 'commercial',
  },

  {
    id: 3,
    firstName: 'Laura',
    lastName: 'Miller',
    age: 32,
    picture: '',
    email: 'sara.miller@test.com',
    phone: '555-1234',
    address: '789 Maple Ave',
    created: new Date(),
    categorie: '',
  },

  {
    id: 4,
    firstName: 'Bob',
    lastName: 'Johnson',
    age: 21,
    picture: '',
    email: 'bob.miller@test.com',
    phone: '555-7890',
    address: '101 Oak St',
    created: new Date(),
    categorie: '',
  },

  {
    id: 5,
    firstName: 'Anna',
    lastName: 'Doe',
    age: 50,
    picture: '',
    email: 'laura.doe@test.com',
    phone: '555-7890',
    address: '789 Maple Ave',
    created: new Date(),
    categorie: 'dev',
  },

  {
    id: 6,
    firstName: 'Alice',
    lastName: 'Williams',
    age: 91,
    picture: 'https://example.com/assets/images/person1.png',
    email: 'anna.davis@mail.com',
    phone: '555-9012',
    address: '202 Pine St',
    created: new Date(),
    categorie: 'ingenieur',
  },

  {
    id: 7,
    firstName: 'Gary',
    lastName: 'Williams',
    age: 41,
    picture: 'https://example.com/assets/images/person1.png',
    email: 'anna.davis@mail.com',
    phone: '555-7890',
    address: '456 Elm St',
    created: new Date(),
    categorie: 'ingenieur',
  },

  {
    id: 8,
    firstName: 'Jane',
    lastName: 'Garcia',
    age: 40,
    picture: 'https://example.com/assets/images/person2.png',
    email: 'john.davis@example.com',
    phone: '555-7890',
    address: '789 Maple Ave',
    created: new Date(),
    categorie: '',
  },

  {
    id: 9,
    firstName: 'Alice',
    lastName: 'Davis',
    age: 24,
    picture: 'https://example.com/assets/images/person3.png',
    email: 'john.williams@test.com',
    phone: '555-7890',
    address: '101 Oak St',
    created: new Date(),
    categorie: 'dev',
  },

  {
    id: 10,
    firstName: 'Alice',
    lastName: 'Smith',
    age: 86,
    picture: 'https://example.com/assets/images/person2.png',
    email: 'bob.davis@mail.com',
    phone: '555-7890',
    address: '789 Maple Ave',
    created: new Date(),
    categorie: 'ingenieur',
  },

  {
    id: 11,
    firstName: 'Paul',
    lastName: 'Brown',
    age: 96,
    picture: '',
    email: 'jane.brown@mail.com',
    phone: '555-3456',
    address: '789 Maple Ave',
    created: new Date(),
    categorie: 'dev',
  },
];
